# Generated by Django 6.0.6 on 2026-06-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200, verbose_name='Médico responsable')),
                ('patient_code', models.CharField(help_text='Identificador anónimo del paciente.', max_length=50, verbose_name='Código de paciente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas clínicas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('symptoms_input', models.JSONField(help_text='Diccionario síntoma→intensidad enviado por el formulario.', verbose_name='Síntomas ingresados (JSON)')),
            ],
            options={
                'verbose_name': 'Caso clínico',
                'verbose_name_plural': 'Casos clínicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('clinical_criteria', models.TextField(blank=True, help_text='Criterios diagnósticos formales, derivaciones o exámenes sugeridos.', verbose_name='Criterios clínicos / notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría médica',
                'verbose_name_plural': 'Categorías médicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('relevance_level', models.IntegerField(choices=[(1, 'Común / Menor (peso 1)'), (3, 'Patognomónico / Mayor (peso 3)')], default=1, help_text='Define el peso base del síntoma para el motor de inferencia.', verbose_name='Nivel de relevancia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Síntoma',
                'verbose_name_plural': 'Síntomas',
                'ordering': ['-relevance_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('treatment_type', models.CharField(choices=[('FARM', 'Farmacológico'), ('QUIR', 'Quirúrgico'), ('FISI', 'Fisioterapéutico'), ('DIET', 'Dietético / Nutricional'), ('DERI', 'Derivación a especialista'), ('OTRO', 'Otro')], default='FARM', max_length=4, verbose_name='Tipo de tratamiento')),
                ('application_conditions', models.TextField(help_text='Cuándo y cómo aplicar este tratamiento.', verbose_name='Condiciones de aplicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Puntaje calculado')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Posición en el ranking')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recomendación / exámenes sugeridos')),
                ('clinical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.clinicalcase', verbose_name='Caso clínico')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_results', to='core.disease', verbose_name='Enfermedad sugerida')),
            ],
            options={
                'verbose_name': 'Resultado de diagnóstico',
                'verbose_name_plural': 'Resultados de diagnóstico',
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='core.medicalcategory', verbose_name='Categoría médica'),
        ),
        migrations.CreateModel(
            name='DiseaseSymptomRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_weight', models.IntegerField(choices=[(1, 'Menor (1)'), (3, 'Mayor / Patognomónico (3)')], default=1, help_text='Peso formal de esta relación para el motor de inferencia.', verbose_name='Peso de asociación')),
                ('notes', models.TextField(blank=True, help_text='Observaciones clínicas adicionales sobre esta relación.', verbose_name='Notas')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_relations', to='core.disease', verbose_name='Enfermedad')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.symptom', verbose_name='Síntoma')),
            ],
            options={
                'verbose_name': 'Relación Enfermedad–Síntoma',
                'verbose_name_plural': 'Relaciones Enfermedad–Síntoma',
                'ordering': ['-association_weight'],
                'unique_together': {('disease', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatmentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_conditions', models.TextField(help_text='Condiciones específicas para aplicar este tratamiento a esta enfermedad.', verbose_name='Condiciones formales de aplicación')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 = primera línea, 2 = segunda línea, etc.', verbose_name='Prioridad')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_relations', to='core.disease', verbose_name='Enfermedad')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.treatment', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Relación Enfermedad–Tratamiento',
                'verbose_name_plural': 'Relaciones Enfermedad–Tratamiento',
                'ordering': ['priority'],
                'unique_together': {('disease', 'treatment')},
            },
        ),
    ]
