# Generated by Django 6.0.6 on 2026-06-20 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clinicalcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Caso clinico'},
        ),
        migrations.AlterModelOptions(
            name='diagnosisresult',
            options={'ordering': ['rank'], 'verbose_name': 'Resultado de diagnostico'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Enfermedad'},
        ),
        migrations.AlterModelOptions(
            name='diseasesymptomrelation',
            options={'ordering': ['-association_weight'], 'verbose_name': 'Relacion Enfermedad-Sintoma'},
        ),
        migrations.AlterModelOptions(
            name='diseasetreatmentrelation',
            options={'ordering': ['priority'], 'verbose_name': 'Relacion Enfermedad-Tratamiento'},
        ),
        migrations.AlterModelOptions(
            name='medicalcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria medica'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-relevance_level', 'name'], 'verbose_name': 'Sintoma'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['name'], 'verbose_name': 'Tratamiento'},
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='doctor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='patient_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='symptoms_input',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='clinical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.clinicalcase'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_results', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='core.medicalcategory'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='clinical_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='association_weight',
            field=models.IntegerField(choices=[(1, 'Menor'), (3, 'Mayor')], default=1),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_relations', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.symptom'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_relations', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='formal_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.treatment'),
        ),
        migrations.AlterField(
            model_name='medicalcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='relevance_level',
            field=models.IntegerField(choices=[(1, 'Comun / Menor'), (3, 'Patognomonico / Mayor')], default=1),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='application_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('FARM', 'Farmacologico'), ('QUIR', 'Quirurgico'), ('FISI', 'Fisioterapeutico'), ('DIET', 'Dietetico'), ('DERI', 'Derivacion'), ('OTRO', 'Otro')], default='FARM', max_length=4),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('other_allergies', models.TextField(blank=True)),
                ('medical_background', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='patients', to='core.allergy')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'code')},
            },
        ),
    ]
