# Generated by Django 6.0.6 on 2026-07-01 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allergy_alter_clinicalcase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Caso clinico', 'verbose_name_plural': 'Casos clinicos'},
        ),
        migrations.AlterModelOptions(
            name='diagnosisresult',
            options={'ordering': ['rank'], 'verbose_name': 'Resultado de diagnostico', 'verbose_name_plural': 'Resultados de diagnostico'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades'},
        ),
        migrations.AlterModelOptions(
            name='diseasesymptomrelation',
            options={'ordering': ['-association_weight'], 'verbose_name': 'Relacion Enfermedad-Sintoma', 'verbose_name_plural': 'Relaciones Enfermedad-Sintoma'},
        ),
        migrations.AlterModelOptions(
            name='diseasetreatmentrelation',
            options={'ordering': ['priority'], 'verbose_name': 'Relacion Enfermedad-Tratamiento', 'verbose_name_plural': 'Relaciones Enfermedad-Tratamiento'},
        ),
        migrations.AlterModelOptions(
            name='medicalcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria medica', 'verbose_name_plural': 'Categorias medicas'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-relevance_level', 'name'], 'verbose_name': 'Sintoma', 'verbose_name_plural': 'Sintomas'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['name'], 'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterField(
            model_name='allergy',
            name='category',
            field=models.CharField(blank=True, max_length=80, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='doctor_name',
            field=models.CharField(max_length=200, verbose_name='Medico responsable'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas clinicas adicionales'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='patient_code',
            field=models.CharField(max_length=50, verbose_name='Codigo de paciente'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='symptoms_input',
            field=models.JSONField(verbose_name='Sintomas ingresados (JSON)'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='clinical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.clinicalcase', verbose_name='Caso clinico'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_results', to='core.disease', verbose_name='Enfermedad sugerida'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='rank',
            field=models.PositiveSmallIntegerField(verbose_name='Posicion en el ranking'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Recomendacion / examenes sugeridos'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='score',
            field=models.FloatField(verbose_name='Puntaje calculado'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='core.medicalcategory', verbose_name='Categoria medica'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='clinical_criteria',
            field=models.TextField(blank=True, verbose_name='Criterios clinicos / notas'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='association_weight',
            field=models.IntegerField(choices=[(1, 'Menor (1)'), (3, 'Mayor / Patognomonico (3)')], default=1, verbose_name='Peso de asociacion'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_relations', to='core.disease', verbose_name='Enfermedad'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='diseasesymptomrelation',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.symptom', verbose_name='Sintoma'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_relations', to='core.disease', verbose_name='Enfermedad'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='formal_conditions',
            field=models.TextField(verbose_name='Condiciones formales de aplicacion'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='diseasetreatmentrelation',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='core.treatment', verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='medicalcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='medicalcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', to='core.allergy', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Codigo de paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Medico responsable'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_background',
            field=models.TextField(blank=True, verbose_name='Antecedentes medicos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_allergies',
            field=models.TextField(blank=True, verbose_name='Otras alergias'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='relevance_level',
            field=models.IntegerField(choices=[(1, 'Comun / Menor (peso 1)'), (3, 'Patognomonico / Mayor (peso 3)')], default=1, verbose_name='Nivel de relevancia'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='application_conditions',
            field=models.TextField(verbose_name='Condiciones de aplicacion'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('FARM', 'Farmacologico'), ('QUIR', 'Quirurgico'), ('FISI', 'Fisioterapeutico'), ('DIET', 'Dietetico / Nutricional'), ('DERI', 'Derivacion a especialista'), ('OTRO', 'Otro')], default='FARM', max_length=4, verbose_name='Tipo de tratamiento'),
        ),
    ]
