# Generated by Django 6.0.6 on 2026-07-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clinicalcase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cie10_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo CIE-10'),
        ),
        migrations.AddField(
            model_name='disease',
            name='cie11_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo CIE-11'),
        ),
        migrations.AddField(
            model_name='disease',
            name='reunis_capitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Capitulo REUNIS'),
        ),
    ]
